cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv
dist: xenial
env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
    - PYENV_ROOT="$HOME/.pyenv"
    - PATH="$PYENV_ROOT/bin:$PATH"
    - PIP_CACHE_DIR="$HOME/.cache/pip"  # unify pip cache location for all platforms
stages:
  - test
  - build
# Each job will use the previous job's `stage` tag if not specified.
jobs:
  include:
  # test jobs
  - name: "3.7 on Windows"
    stage: test
    os: windows
    language: shell
  - name: "3.5 on Linux"
    language: python
    python: 3.5
  - name: "3.6 on Linux"
    language: python
    python: 3.6
  - name: "3.7 on Linux"
    language: python
    python: 3.7
  - name: "3.7 on Mac"
    os: osx
    osx_image: xcode11.3
  # build jobs
  - name: "Pypi pkgs"
    if: tag is present
    stage: build
    language: python
    python: 3.7
    script: ./scripts/build_package.sh
    deploy:
    - provider: pypi
      user:
        secure: "dVgOv8b7k7TSPZBJgBP3vHWRkTzCMb0rw+HuM8GMggMDrOHnBuDNqK90tazUDajAEbNf/gCgeOH0+Ty+wKVEl4iV16f77skqU4gyZkQTXXpTIDoMFCSsh9X2o8AWRLwasOGYOE5wT+JyCRww/v8gANNiUC4DYRDqcxgvj/ZOGNjdENkqvGbjI2OjIbqsvArxnB5EDzbmem28uNaE4kqKRUasoz5JhjGXP4+kmloySUUp3JvnL5J2rTXRuguv5Nwb2qS7VCT+nOAIvYtNcz/DfOrSiRjVuRRAHzqqNyF8O3k63CxTM/Fzbve6A1LSz5yMuIGOreniz5BY841bq168QsutmWvZwH7Yhz/l7bcVhY7m+453+Bv4j3HyQ8HcWZ+sWVA/gtFQs7Ma/FFbeHMXE9YVsL+2vZaAsfBoC6ZXqYGa2u747vaw9HOqX9qNsnuAh+KIFhPG1OxCTjvH09TR3DdNSZL4kny85Wva4FZs9sQTXSABG/XBkvkiwaVjfoc+GQsAYlZcdejGZFGcy7jdwcmcR04hnJdPX27Q/HmSm2vu4bLxBdJ/7c1kZnt4Z7VWq0HRj/pbnANFJsuCuPV5WmrLUPu8nVE4n3j1M4EbgVJk49PxWfFahNNHtJ6GVUfUcA/ul4F20gxGj4S4TuBM8aqq7nX2TdvaPkwQ3EvdGRU="
      password:
        secure: "TUP276aiiktQMiFXtdf5MXSe9dOQPWgvueA+mWAqUTemsZDg/2Ca4ZeoWtxidlDmVxVPwqF4ApMWjBOzxkP/5YnbLPUqWBm80QP+CtXHq6uSFY1Mq6WEHGVSo/hMGRvc913o+CaKF1wPZZV6uH9IuXuirnkmJaFprhqpNh0doxuFtjmH60WTPRHYlgObuOWfnDSA9TP8lpgEJ1G2xXqrTYXGEqKn5GwtYuTzxDOmn2J8AnT86eG2FWSiRnOw7PTOIW4HKneaXadkioTwMxyE1cehaqzhdi5gnyPPkbFwMmTUiY7bvxEcvc5YIBxojBqkX8dxuBRRVmul5o6E8UwxVEyoUoMhLfGbzh1Fvmpjk8PloTG9RGPjg42tkU91EBpOrXeUZaLIRrMPm3GQ2bcivVd10Xqx6a3/k7YedgNw6e+3pMHh4zNepjYelK8s+L19xFRTZ7D81u5DIa30qXmO0ZgWEkBsDJy14zADaju4LM/+wE3dUgwNzPplhIQ24vHiHZXhg+4nuzGNR9FwCOkmGJGxJeELkqqJWUIASP2WsDYq2gK1sEDg93qPyMwqUfYhU9JtlGb/VR0b1a51LqoavDvvjDNAXb5nxnG0LGGGIS9imMa+sea9iCmdfwS3KyCjbzuWaQ14rKME6nCt/rmwfexcq9InDSyHDteIuREfnfs="
      skip_existing: true
      file_glob: true
      file:
        - dist/pydrive2*.whl
        - dist/pydrive2*.tar.gz
      skip_cleanup: true
      on:
        tags: true
        repo: iterative/PyDrive2

before_install:
  - bash ./scripts/ci/before_install.sh
  - source env.sh
  - bash ./scripts/ci/check_python.sh
install:
  - bash ./scripts/ci/install.sh
script:
  - bash ./scripts/ci/script.sh
